[alias]
valida_config = [
    "--config", 'build.target="valida-unknown-baremetal-gnu"',
    "--config", 'target.valida-unknown-baremetal-gnu.linker="/valida-toolchain/bin/ld.lld"',
    "--config", 'target.valida-unknown-baremetal-gnu.runner="echo to run the code try valida run "',
    "--config", 'target.valida-unknown-baremetal-gnu.rustflags=["-C","link-arg=/valida-toolchain/validaEntryPoint.o","-C","link-arg=--script=/valida-toolchain/valida.ld","-C","link-arg=/valida-toolchain/lib/valida-unknown-baremetal-gnu/libc.a","-C","link-arg=/valida-toolchain/lib/valida-unknown-baremetal-gnu/libm.a","-C","link-arg=--noinhibit-exec"]',
    "--config", 'env.CC_valida_unknown_baremetal_gnu="/valida-toolchain/bin/clang"',
    "--config", 'env.CFLAGS_valida_unknown_baremetal_gnu="--sysroot=/valida-toolchain/ -isystem /valida-toolchain/include"',
]
