[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "testing"
path = "src/main.rs"

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
entrypoint = { path = "../../" }
